from . import prestashop_api
from . import prestashop_config
from . import prestashop_category
from . import prestashop_product
from . import prestashop_customer
from . import prestashop_order
from . import product_template
from . import prestashop_product_combination
from . import sale_order
from . import stock_picking